/**
 *     _____ __
 *    |__   /  / _
 *      /  /  /_| |_
 *     /  /\____   _|
 *    /_____|   |_|
 *
 * @file logger.ts
 * @author Etienne Cochard
 *
 * @copyright (c) 2026 R-libre ingenierie
 *
 * Use of this source code is governed by an MIT-style license
 * that can be found in the LICENSE file or at https://opensource.org/licenses/MIT.
 **/

// Logger and security log.
//
// Line format (one event per line):
//
//   <ISO date time UTC> <LEVEL> <request id or -> <event> [<json data>]
//
// Everything before the JSON part is produced by z4js itself: the event name is
// checked against a strict pattern (or a closed list for security events) and the
// request id is generated by z4js. Anything coming from a client goes only in the
// JSON part, where newlines are escaped and strings are truncated, so a client can
// never forge a log line.
//
// Destination: null = standard output (standard error from "error" up),
// otherwise a file path where ${date} (UTC, YYYY-MM-DD) is the only accepted token.

import { appendFileSync, createWriteStream, statSync, type WriteStream } from "node:fs";
import { dirname } from "node:path";

// from the most to the least verbose: the type and the ranks derive from this list
export const LOG_LEVELS = ["debug", "info", "warn", "error", "fatal"] as const;

export type LogLevel = ( typeof LOG_LEVELS )[number];

const RANK = Object.fromEntries( LOG_LEVELS.map( ( level, i ) => [level, i] ) ) as Record<LogLevel, number>;

// longest string value kept in the JSON part (anything longer is cut)
const MAX_STRING = 256;

// above this many pending bytes, low level lines are dropped (and counted)
const MAX_PENDING_BYTES = 1024 * 1024;

const EVENT_RE = /^[a-z][a-z0-9._-]{0,63}$/;
const REQUEST_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;
const DATE_TOKEN = "${date}";

// ---------------------------------------------------------------------------

function checkEvent( event: string ) {
	// a bad event name is a programming error, not a runtime condition
	if( !EVENT_RE.test( event ) ) {
		throw new Error( "log: invalid event name" );
	}
}

function checkRequestId( id: string ) {
	if( !REQUEST_ID_RE.test( id ) ) {
		throw new Error( "log: invalid request id" );
	}
}

function utcDate( ) {
	return new Date( ).toISOString( ).slice( 0, 10 );
}

function safeJson( data: Record<string, unknown>, withStack: boolean ): string {
	const replacer = ( _key: string, value: unknown ) => {
		if( typeof value === "string" ) {
			return value.length > MAX_STRING ? value.slice( 0, MAX_STRING ) + "…" : value;
		}

		if( typeof value === "bigint" ) {
			return value.toString( );
		}

		if( value instanceof Error ) {
			const err: Record<string, unknown> = { name: value.name, message: value.message };
			if( withStack && value.stack ) {
				err.stack = value.stack;
			}
			return err;
		}

		return value;
	};

	let json: string;
	try {
		json = JSON.stringify( data, replacer );
	}
	catch {
		// circular structure or similar: never let logging throw
		json = '{"log":"unserializable"}';
	}

	// JSON.stringify leaves these two as they are, but some tools treat them as line breaks
	return json.replaceAll( "\u2028", "\\u2028" ).replaceAll( "\u2029", "\\u2029" );
}

function formatLine(
	level: string,
	requestId: string,
	event: string,
	data?: Record<string, unknown>,
	withStack = false
) {
	let line = `${new Date( ).toISOString( )} ${level} ${requestId ?? "-"} ${event}`;
	if( data !== undefined ) {
		line += " " + safeJson( data, withStack );
	}

	return line + "\n";
}

function reportFileFailure( ) {
	process.stderr.write( formatLine( "ERROR", undefined, "log.file.failed" ) );
}

// ---------------------------------------------------------------------------

interface WriteOptions {
	stderr: boolean;		// standard error instead of standard output (no file)
	droppable: boolean;		// may be dropped when the file is too slow
	sync: boolean;			// written synchronously (fatal errors: the process may exit right after)
}

// owns the destination: standard streams, or an append-only file following ${date}
class Sink {
	private stream: WriteStream = null;
	private streamPath = "";
	private dropped = 0;

	constructor( private readonly template: string, private readonly mode: number ) {
		if( template === null ) {
			return;
		}

		if( template.replaceAll( DATE_TOKEN, "" ).includes( "${" ) ) {
			throw new Error( "log file: only ${date} is accepted in the path" );
		}

		const dir = dirname( template );
		if( dir.includes( DATE_TOKEN ) ) {
			throw new Error( "log file: ${date} is accepted in the file name only" );
		}

		// the folder must already exist: it is created (or not) at init, never here
		if( !statSync( dir ).isDirectory( ) ) {
			throw new Error( "log file: the parent is not a folder" );
		}
	}

	write( line: string, opts: WriteOptions ) {
		if( this.template === null ) {
			( opts.stderr ? process.stderr : process.stdout ).write( line );
			return;
		}

		const path = this.template.replaceAll( DATE_TOKEN, utcDate( ) );

		try {
			if( opts.sync ) {
				appendFileSync( path, line, { mode: this.mode } );
				return;
			}

			const stream = this.open( path );

			if( opts.droppable && stream.writableLength > MAX_PENDING_BYTES ) {
				this.dropped++;
				return;
			}

			if( this.dropped > 0 ) {
				stream.write( formatLine( "WARN", undefined, "log.dropped", { count: this.dropped } ) );
				this.dropped = 0;
			}

			stream.write( line );
		}
		catch {
			this.fallback( line );
		}
	}

	close( ) {
		this.stream?.end( );
		this.stream = null;
	}

	// a line is never lost silently: if the file fails, it goes to standard error
	private fallback( line: string ) {
		reportFileFailure( );
		process.stderr.write( line );
	}

	private open( path: string ): WriteStream {
		if( this.stream && this.streamPath === path ) {
			return this.stream;
		}

		// date changed (or first write): move to the new file
		this.stream?.end( );

		const stream = createWriteStream( path, { flags: "a", mode: this.mode } );
		stream.on( "error", ( ) => {
			reportFileFailure( );
			if( this.stream === stream ) {
				this.stream = null;
			}
		} );

		this.stream = stream;
		this.streamPath = path;
		return stream;
	}
}

// ---------------------------------------------------------------------------

export interface LoggerOptions {
	level: LogLevel;				// minimal level written
	file?: string;			// null or absent = standard output/error
	mode?: number;					// file permissions, owner only by default
}

interface Core {
	sink: Sink;
	min: number;
}

// the application log: one line per event, filtered by level, written to the
// standard output or to a file. child( ) gives the logger of one request
export class Logger {
	private constructor( private readonly core: Core, private readonly requestId?: string ) {
	}

	static create( options: LoggerOptions ): Logger {
		return new Logger( {
			sink: new Sink( options.file ?? null, options.mode ?? 0o600 ),
			min: RANK[options.level]
		} );
	}

	// same destination, every line carries the given request id (generated by z4js)
	child( requestId: string ): Logger {
		checkRequestId( requestId );
		return new Logger( this.core, requestId );
	}

	debug( event: string, data?: Record<string, unknown> ) { this.log( "debug", event, data ); }
	info( event: string, data?: Record<string, unknown> ) { this.log( "info", event, data ); }
	warn( event: string, data?: Record<string, unknown> ) { this.log( "warn", event, data ); }
	error( event: string, data?: Record<string, unknown> ) { this.log( "error", event, data ); }
	fatal( event: string, data?: Record<string, unknown> ) {
		this.log( "fatal", event, data );

		// debug level: stop in the debugger, the line is already written (sync).
		// "debugger" does nothing when no debugger is attached
		if( this.core.min === RANK.debug ) {
			debugger;
		}
	}

	close( ) {
		this.core.sink.close( );
	}

	private log( level: LogLevel, event: string, data?: Record<string, unknown> ) {
		checkEvent( event );

		const rank = RANK[level];
		if( rank < this.core.min ) {
			return;
		}

		const line = formatLine( level.toUpperCase( ), this.requestId, event, data, rank >= RANK.error );

		this.core.sink.write( line, {
			stderr: rank >= RANK.error,
			droppable: rank < RANK.warn,
			sync: level === "fatal"
		} );
	}
}

// ---------------------------------------------------------------------------

// closed list: a name outside of it is a programming error
export const SECURITY_EVENTS = [
	"auth.login.ok",
	"auth.login.failed",
	"auth.unauthorized",
	"auth.forbidden",
	"auth.stepup.required",
	"auth.stepup.ok",
	"auth.stepup.failed",
	"auth.session.revoked",
	"auth.ticket.refused",
	"auth.rights.changed"
] as const;

export type SecurityEvent = ( typeof SECURITY_EVENTS )[number];

export interface SecurityLogOptions {
	file?: string;			// own destination, same rules as the logger
	mode?: number;
	extraEvents?: readonly string[];	// events added by the application
}

// same line format, fixed level "SEC", never filtered by level and never dropped
export class SecurityLog {
	private readonly sink: Sink;
	private readonly allowed: ReadonlySet<string>;

	constructor( options: SecurityLogOptions = {} ) {
		const extra = options.extraEvents ?? [];
		extra.forEach( checkEvent );

		this.allowed = new Set<string>( [...SECURITY_EVENTS, ...extra] );
		this.sink = new Sink( options.file ?? null, options.mode ?? 0o600 );
	}

	log( event: string, data?: Record<string, unknown>, requestId?: string ) {
		if( !this.allowed.has( event ) ) {
			throw new Error( "security log: unknown event" );
		}

		if( requestId !== undefined ) {
			checkRequestId( requestId );
		}

		this.sink.write( formatLine( "SEC", requestId, event, data ), {
			stderr: false,
			droppable: false,
			sync: false
		} );
	}

	close( ) {
		this.sink.close( );
	}
}
