/**
 *     _____ __
 *    |__   /  / _
 *      /  /  /_| |_
 *     /  /\____   _|
 *    /_____|   |_|
 *
 * @file server.ts
 * @author Etienne Cochard
 *
 * @copyright (c) 2026 R-libre ingenierie
 *
 * Use of this source code is governed by an MIT-style license
 * that can be found in the LICENSE file or at https://opensource.org/licenses/MIT.
 **/

// Assembly of the HTTP(S) server, from the configuration and the route groups:
// Express, TLS, timeouts, body limit, CORS, security headers, request ids, route
// groups, static folders, WebSockets and the clean shutdown.
//
//   const config = Config.load( AppConfig );
//   const logger = Logger.create( config.log );
//   const api = RouteGroup.guarded( "/api/v1", sessionGuard ).add( "/bed", bedEP );
//   await serve( { config, logger, groups: [api], statics: [{ path: "/", folder: config.www }] } );

import { randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { createServer as createHttpServer } from "node:http";
import type { Server } from "node:http";
import { createServer as createHttpsServer } from "node:https";
import express from "express";
import type { RequestHandler } from "express";
import { isAccessChecked } from "./access";
import type { Config } from "./config";
import type { RouteGroup } from "./endpoints";
import { createErrorHandler, notFoundHandler } from "./http-handlers";
import type { Logger } from "./logger";
import { checkFixedPath, routeKey } from "./paths";
import { RateLimiter } from "./ratelimit";
import { createUpgradeHandler } from "./ws";

declare global {
	namespace Express {
		interface Request {
			// id of the request, generated by z4js, also sent back in X-Request-Id
			id: string;
			// logger whose lines carry the request id
			log: Logger;
			// set by the guard of a guarded group (session)
			user?: any;
			// the session of the request, set by the guard (session.ts)
			session?: { id: string, stepUpUntil: number };
		}
	}
}

const HSTS = "max-age=31536000";
const CORS_METHODS = "GET, POST, PUT, PATCH, DELETE";
const CORS_HEADERS = "Authorization, Content-Type";
const CORS_MAX_AGE = "600";

export interface StaticFolder {
	path: string;		// url path, "/" for the root
	folder: string;		// absolute folder (read from the configuration)
}

export interface ServeOptions {
	config: Config;
	logger: Logger;
	groups: readonly RouteGroup[];
	// served without any control: index.html, no listing, dot files ignored
	statics?: readonly StaticFolder[];
	// SIGTERM and SIGINT stop the server cleanly (default true)
	handleSignals?: boolean;
	// called by close( ) once the HTTP requests are over: stops the rest (workers.stop...)
	onStop?: ( ) => Promise<void>;
}

export interface RunningServer {
	readonly server: Server;
	// stops accepting connections, closes the WebSockets, lets the running requests
	// end (config.server.shutdownMs at most, then cuts them)
	close( ): Promise<void>;
}

export async function serve( options: ServeOptions ): Promise<RunningServer> {
	const { config, logger, groups } = options;
	const { server: cfg } = config;
	const tls = !!config.tls.cert;

	checkGroups( groups );

	const app = express( );
	app.disable( "x-powered-by" );
	app.set( "trust proxy", cfg.trustProxy );

	app.use( requestLog( logger, cfg.slowRequestMs, config.debug ) );
	app.use( securityHeaders( tls ) );

	app.use( cors( cfg.cors ) );

	// only an object or an array is accepted as JSON body
	app.use( express.json( { limit: cfg.bodyLimit, strict: true } ) );

	// every route of the groups, per IP (not the static files)
	const perIp = config.rateLimit.apiPerMinute;
	const apiLimit: RequestHandler = perIp > 0 ? new RateLimiter( "api", perIp, 60_000 ).filter : ( _req, _res, next ) => next( );

	for( const group of groups ) {
		app.use( group.prefix, apiLimit, noStore, group.toRouter( ) );
		logger.info( "server.routes", {
			prefix: group.prefix,
			routes: group.list( ).map( r => `${r.method} ${r.path}${r.guarded ? "" : " (unprotected)"}` )
		} );
	}

	for( const { path, folder } of options.statics ?? [] ) {
		checkFixedPath( path );
		app.use( path, express.static( folder, { dotfiles: "ignore", redirect: false } ) );
	}

	app.use( notFoundHandler );
	app.use( createErrorHandler( logger ) );

	const server = tls
		? createHttpsServer( { cert: readFileSync( config.tls.cert ), key: config.tls.key }, app )
		: createHttpServer( app );

	server.headersTimeout = cfg.headersTimeoutMs;
	server.requestTimeout = cfg.requestTimeoutMs;
	server.keepAliveTimeout = cfg.keepAliveTimeoutMs;

	const sockets = createUpgradeHandler( groups, { logger } );
	server.on( "upgrade", sockets.upgrade );

	await new Promise<void>( ( resolve, reject ) => {
		server.once( "error", reject );
		server.listen( cfg.port, cfg.host, ( ) => {
			server.off( "error", reject );
			resolve( );
		} );
	} );

	logger.info( "server.started", { url: `${tls ? "https" : "http"}://${cfg.host}:${cfg.port}` } );

	let closing: Promise<void> = null;

	const close = ( ) => closing ??= new Promise<void>( resolve => {
		logger.info( "server.stopping" );
		sockets.close( );

		const timer = setTimeout( ( ) => server.closeAllConnections( ), cfg.shutdownMs );
		server.close( async ( ) => {
			clearTimeout( timer );

			try {
				await options.onStop?.( );
			}
			catch( e ) {
				logger.error( "server.stop.failed", { error: e } );
			}

			logger.info( "server.stopped" );
			resolve( );
		} );

		// kept alive connections with no running request would hold server.close
		server.closeIdleConnections( );
	} );

	if( options.handleSignals ?? true ) {
		for( const signal of ["SIGTERM", "SIGINT"] as const ) {
			process.once( signal, ( ) => void close( ) );
		}
	}

	return { server, close };
}

// a route declared in two groups would be served by the first one mounted only: an
// unprotected group could hide a route of a guarded one. refused at startup
function checkGroups( groups: readonly RouteGroup[] ) {
	const keys = new Set<string>( );

	for( const group of groups ) {
		for( const route of group.list( ) ) {
			const key = routeKey( route.method, route.path );
			if( keys.has( key ) ) {
				throw new Error( `route ${key} declared in two groups` );
			}

			keys.add( key );
		}
	}
}

// gives each request its id (generated here, never taken from the client: a log line
// cannot be forged) and logs it once answered. the time runs until the answer is sent
// ("finish"), so an async handler is measured whole; above slowMs, it is a warning.
// "close" without "finish": the client left before the answer.
// debug: a successful answer of a guarded route (req.user set by the guard) given
// without any access check (userHasAccess or noAccessCheck) is a warning
function requestLog( logger: Logger, slowMs: number, debug: boolean ): RequestHandler {
	return ( req, res, next ) => {
		req.id = randomBytes( 9 ).toString( "base64url" );
		req.log = logger.child( req.id );
		res.setHeader( "X-Request-Id", req.id );

		const start = Date.now( );
		// the full path, before the routers cut their prefix. no query string: it may hold a ticket
		const data = { method: req.method, path: req.path };

		res.once( "finish", ( ) => {
			const ms = Date.now( ) - start;
			const line = { ...data, status: res.statusCode, ms };

			// res.locals.expectedSlow: slow by design (password hashing at login)
			if( ms > slowMs && !res.locals.expectedSlow ) {
				req.log.warn( "http.slow", line );
			}
			else {
				req.log.info( "http.request", line );
			}

			if( debug && req.user && res.statusCode < 400 && !isAccessChecked( req.user ) ) {
				req.log.warn( "access.unchecked", data );
			}
		} );

		res.once( "close", ( ) => {
			if( !res.writableFinished ) {
				req.log.warn( "http.aborted", { ...data, ms: Date.now( ) - start } );
			}
		} );

		next( );
	};
}

function securityHeaders( tls: boolean ): RequestHandler {
	return ( _req, res, next ) => {
		res.setHeader( "X-Content-Type-Options", "nosniff" );
		if( tls ) {
			res.setHeader( "Strict-Transport-Security", HSTS );
		}

		next( );
	};
}

// API answers are never cached (static files are)
const noStore: RequestHandler = ( _req, res, next ) => {
	res.setHeader( "Cache-Control", "no-store" );
	next( );
};

// an allowed origin gets the CORS headers, any other gets none and the browser blocks
// the answer. no credentials: z4js has no cookie. no route answers OPTIONS: anything
// but the preflight of an allowed origin is a plain 404 (Express would list the methods)
function cors( origins: readonly string[] ): RequestHandler {
	const allowed = new Set( origins );

	return ( req, res, next ) => {
		res.vary( "Origin" );

		const origin = req.headers.origin;
		if( !origin || !allowed.has( origin ) ) {
			if( req.method === "OPTIONS" ) {
				notFoundHandler( req, res, next );
			}
			else {
				next( );
			}
			return;
		}

		res.setHeader( "Access-Control-Allow-Origin", origin );
		res.setHeader( "Access-Control-Expose-Headers", "X-Request-Id" );

		// preflight: answered here, the route itself is not called
		if( req.method === "OPTIONS" ) {
			res.setHeader( "Access-Control-Allow-Methods", CORS_METHODS );
			res.setHeader( "Access-Control-Allow-Headers", CORS_HEADERS );
			res.setHeader( "Access-Control-Max-Age", CORS_MAX_AGE );
			res.status( 204 ).end( );
			return;
		}

		next( );
	};
}
